### ISSUE TITLE
Design speaker cards for Twitter

### ISSUE THREAD

**Issue by jchiatt** [jchiatt/magnoliajs.com#10]
Speaker cards are really helpful because they are a visual way to draw attention to the conference on social media.

We need speaker cards that have:

* name
* company
* twitter handle
* talk title
* MagnoliaJS logo
* Jackson, Mississippi
* April 18, 2019

Sketch file (with logo) available here: https://jchiatt.d.pr/HTfHVu

**Comment by jalendport** [comment]
Claimed!

**Comment by jchiatt** [comment]
Great job @jalendport!

https://twitter.com/jchiatt/status/1110540029720477697

**Comment by jalendport** [comment]
@jchiatt thanks! My pleasure...
