### ISSUE TITLE
Design workshop cards for Twitter

### ISSUE THREAD

**Issue by jchiatt** [jchiatt/magnoliajs.com#11]
Workshop cards are really helpful because they are a visual way to draw attention to the conference on social media.

We need workshop cards that have:

* name
* company
* twitter handle
* workshop title
* MagnoliaJS logo
* Jackson, Mississippi
* April 17-18, 2019

Sketch file (with logo) available here: https://jchiatt.d.pr/HTfHVu

**Comment by jalendport** [comment]
Claimed!

**Comment by jchiatt** [comment]
Here's the workshop data: https://www.notion.so/jchiatt/Workshop-Info-bd74aa5092074071bbffddb3dfd80ab2
