### ISSUE TITLE
Speaker cards and pages

### ISSUE THREAD

**Issue by jchiatt** [jchiatt/magnoliajs.com#7]
Users should be able to:

* See a grid of speaker cards with: 
  * name
  * photo
  * company
  * twitter handle
  * talk title

* Click a speaker card to see a page or modal with:
  * the full talk details
  * a link to purchase tickets ([here](https://ti.to/magnoliajs/magnoliajs-2019)

* See 3-4 speaker cards on the homepage, with a link to "View all speakers"

**Comment by petercr** [comment]
I would be happy to help out on this 😎 👍 
Do you have all the information to fill in, or should I just try to get it from Twitter based on the pictures in `/images`?

Either way I'm happy to help out, just let me know

**Comment by lvrbrtsn** [comment]
Hey @petercr I actually had already begun work on this before the issue was made, part of the work was already merged in db0046b I am actually working on wrapping the rest right now.

**Comment by lvrbrtsn** [comment]
@petercr Also, I did exactly what you where thinking too, great minds I guess ; )

**Comment by lvrbrtsn** [comment]
I made PR 14 for this https://github.com/jchiatt/magnoliajs.com/pull/14

I am not sure how much time I will have this weekend and the styling could use some love. @petercr would you want to run with it from here? If not that is fine and I will try and add some more this weekend : )

**Comment by petercr** [comment]
Sure @lvrbrtsn looks like you did a pretty good job so far. Looking over PR #14 💯 
 I'll see what I can add to it tonight 👍

**Comment by jchiatt** [comment]
Hey all, here's the speaker data (note there are a few missing pieces - just fill in TBD where applicable): https://www.notion.so/jchiatt/Main-Stage-Speaker-Data-9d280810c9cc403fa6814d66ed938fca

**Comment by jchiatt** [comment]
^ *Main Stage speakers

**Comment by jchiatt** [comment]
@lvrbrtsn @petercr I just merged this into master! It could still use a bit of love (feel free), but it has all the Main Stage info at least!
