### ISSUE TITLE
Select volunteers

### ISSUE THREAD

**Issue by jchiatt** [jchiatt/magnoliajs.com#92]

**Comment by tdfranklin** [comment]
Hey bro!  I know last year you ended up with too many volunteer's, but if you run short this year, my wife is planning on coming and I'm sure she would be willing to help if needed.  Also, if anything else needs doing, don't hesitate to hit me up.  Want to do anything I can to make sure this is the best MagnoliaJS yet!

**Comment by techieeliot** [comment]
I'd love to help organize the volunteers for both days. Please let me know what I can do to help.
